import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { auth } from '../lib/auth';
import SessionProvider from '../components/providers/session-provider';
import './globals.css';
import Header from '../components/header';
import { ThemeProvider } from '@/components/providers/theme-provider';

/** fonts */
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /** get session */
  const session = await auth();

  return (
    <html lang="en" className="h-full w-full">
      <body
        className={cn(
          'relative h-full w-full font-sans antialiased',
          inter.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex flex-col h-full w-full">
            <SessionProvider session={session}>
              <Header />
              {children}
            </SessionProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
