import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { auth } from './api/auth/auth';
import SessionProvider from './api/auth/session-provider';

/** fonts */
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /** get session */
  const session = await auth();

  return (
    <html lang="en" className="h-full w-full">
      <body
        className={cn(
          'relative h-full w-full font-sans antialiased',
          inter.className
        )}
      >
        <main className="relative h-full w-full flex flex-col min-h-screen">
          <SessionProvider session={session}>{children}</SessionProvider>
        </main>
      </body>
    </html>
  );
}
